from datetime import datetime, timezone
from .config import SKIFF


def build_report(github_stats: dict, trends: dict, ai_ideas: str) -> str:
    today = datetime.now(timezone.utc).strftime("%A, %B %d, %Y")
    lines = [
        f"# 📊 Skiff Marketing Report — {today}",
        "",
        "## GitHub Stats",
        f"- ⭐ Stars: **{github_stats.get('stars', 0)}**",
        f"- 🍴 Forks: **{github_stats.get('forks', 0)}**",
        f"- 👀 Watchers: **{github_stats.get('watchers', 0)}**",
        f"- 🐛 Open Issues: **{github_stats.get('open_issues', 0)}**",
    ]

    commits = github_stats.get("recent_commits", [])
    if commits:
        lines += ["", "## Recent Commits"]
        for c in commits[:5]:
            lines.append(f"- [`{c['sha']}`]({c['url']}) {c['message']} — *{c['author']}*")

    open_issues = github_stats.get("open_issues_list", [])
    if open_issues:
        lines += ["", "## Open Issues"]
        for issue in open_issues[:5]:
            labels = ", ".join(issue["labels"]) if issue["labels"] else "unlabeled"
            lines.append(f"- [#{issue['number']}]({issue['url']}) {issue['title']} `{labels}`")

    # Trends section
    lines += ["", "## 🔥 What's Trending (DevOps / Self-Hosted Space)"]
    hn = trends.get("hackernews", [])
    if hn:
        lines.append("\n**HackerNews:**")
        for item in hn[:4]:
            lines.append(f"- {item['title']} ({item['points']} pts)")

    devto = trends.get("devto", [])
    if devto:
        lines.append("\n**Dev.to:**")
        for item in devto[:4]:
            lines.append(f"- {item['title']}")

    gt = trends.get("google_trends", [])
    if gt:
        lines.append("\n**Google Trends (7-day):**")
        lines.append(", ".join(f"{g['keyword']} ({g['score']})" for g in gt))

    # AI Ideas
    lines += ["", "---", "", "## 💡 AI-Generated Ideas & Action Items", "", ai_ideas]
    lines += [
        "",
        "---",
        f"*Generated by Skiff Marketing Agent · {SKIFF['github_url']}*",
    ]

    return "\n".join(lines)


def save_report(report: str, path: str = "marketing_report.md") -> str:
    with open(path, "w", encoding="utf-8") as f:
        f.write(report)
    print(f"[Reporter] Report saved to {path}")
    return path
